//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema_II_2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaskItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.DateTime DeadlineField;
        
        private bool IsCompletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Deadline {
            get {
                return this.DeadlineField;
            }
            set {
                if ((this.DeadlineField.Equals(value) != true)) {
                    this.DeadlineField = value;
                    this.RaisePropertyChanged("Deadline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool IsCompleted {
            get {
                return this.IsCompletedField;
            }
            set {
                if ((this.IsCompletedField.Equals(value) != true)) {
                    this.IsCompletedField = value;
                    this.RaisePropertyChanged("IsCompleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetTasksResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTasks", ReplyAction="*")]
        Tema_II_2.ServiceReference1.GetTasksResponse GetTasks(Tema_II_2.ServiceReference1.GetTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTasks", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema_II_2.ServiceReference1.GetTasksResponse> GetTasksAsync(Tema_II_2.ServiceReference1.GetTasksRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTask", ReplyAction="*")]
        Tema_II_2.ServiceReference1.AddTaskResponse AddTask(Tema_II_2.ServiceReference1.AddTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTask", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema_II_2.ServiceReference1.AddTaskResponse> AddTaskAsync(Tema_II_2.ServiceReference1.AddTaskRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTask", ReplyAction="*")]
        Tema_II_2.ServiceReference1.UpdateTaskResponse UpdateTask(Tema_II_2.ServiceReference1.UpdateTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTask", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema_II_2.ServiceReference1.UpdateTaskResponse> UpdateTaskAsync(Tema_II_2.ServiceReference1.UpdateTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTask", ReplyAction="*")]
        bool DeleteTask(int taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTask", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteTaskAsync(int taskId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasks", Namespace="http://tempuri.org/", Order=0)]
        public Tema_II_2.ServiceReference1.GetTasksRequestBody Body;
        
        public GetTasksRequest() {
        }
        
        public GetTasksRequest(Tema_II_2.ServiceReference1.GetTasksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTasksRequestBody {
        
        public GetTasksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasksResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema_II_2.ServiceReference1.GetTasksResponseBody Body;
        
        public GetTasksResponse() {
        }
        
        public GetTasksResponse(Tema_II_2.ServiceReference1.GetTasksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTasksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema_II_2.ServiceReference1.TaskItem[] GetTasksResult;
        
        public GetTasksResponseBody() {
        }
        
        public GetTasksResponseBody(Tema_II_2.ServiceReference1.TaskItem[] GetTasksResult) {
            this.GetTasksResult = GetTasksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTask", Namespace="http://tempuri.org/", Order=0)]
        public Tema_II_2.ServiceReference1.AddTaskRequestBody Body;
        
        public AddTaskRequest() {
        }
        
        public AddTaskRequest(Tema_II_2.ServiceReference1.AddTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime deadline;
        
        public AddTaskRequestBody() {
        }
        
        public AddTaskRequestBody(string title, string description, System.DateTime deadline) {
            this.title = title;
            this.description = description;
            this.deadline = deadline;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema_II_2.ServiceReference1.AddTaskResponseBody Body;
        
        public AddTaskResponse() {
        }
        
        public AddTaskResponse(Tema_II_2.ServiceReference1.AddTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddTaskResult;
        
        public AddTaskResponseBody() {
        }
        
        public AddTaskResponseBody(int AddTaskResult) {
            this.AddTaskResult = AddTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTask", Namespace="http://tempuri.org/", Order=0)]
        public Tema_II_2.ServiceReference1.UpdateTaskRequestBody Body;
        
        public UpdateTaskRequest() {
        }
        
        public UpdateTaskRequest(Tema_II_2.ServiceReference1.UpdateTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int taskId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime deadline;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isCompleted;
        
        public UpdateTaskRequestBody() {
        }
        
        public UpdateTaskRequestBody(int taskId, string title, string description, System.DateTime deadline, bool isCompleted) {
            this.taskId = taskId;
            this.title = title;
            this.description = description;
            this.deadline = deadline;
            this.isCompleted = isCompleted;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema_II_2.ServiceReference1.UpdateTaskResponseBody Body;
        
        public UpdateTaskResponse() {
        }
        
        public UpdateTaskResponse(Tema_II_2.ServiceReference1.UpdateTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateTaskResult;
        
        public UpdateTaskResponseBody() {
        }
        
        public UpdateTaskResponseBody(bool UpdateTaskResult) {
            this.UpdateTaskResult = UpdateTaskResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Tema_II_2.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Tema_II_2.ServiceReference1.WebService1Soap>, Tema_II_2.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema_II_2.ServiceReference1.GetTasksResponse Tema_II_2.ServiceReference1.WebService1Soap.GetTasks(Tema_II_2.ServiceReference1.GetTasksRequest request) {
            return base.Channel.GetTasks(request);
        }
        
        public Tema_II_2.ServiceReference1.TaskItem[] GetTasks() {
            Tema_II_2.ServiceReference1.GetTasksRequest inValue = new Tema_II_2.ServiceReference1.GetTasksRequest();
            inValue.Body = new Tema_II_2.ServiceReference1.GetTasksRequestBody();
            Tema_II_2.ServiceReference1.GetTasksResponse retVal = ((Tema_II_2.ServiceReference1.WebService1Soap)(this)).GetTasks(inValue);
            return retVal.Body.GetTasksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema_II_2.ServiceReference1.GetTasksResponse> Tema_II_2.ServiceReference1.WebService1Soap.GetTasksAsync(Tema_II_2.ServiceReference1.GetTasksRequest request) {
            return base.Channel.GetTasksAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema_II_2.ServiceReference1.GetTasksResponse> GetTasksAsync() {
            Tema_II_2.ServiceReference1.GetTasksRequest inValue = new Tema_II_2.ServiceReference1.GetTasksRequest();
            inValue.Body = new Tema_II_2.ServiceReference1.GetTasksRequestBody();
            return ((Tema_II_2.ServiceReference1.WebService1Soap)(this)).GetTasksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema_II_2.ServiceReference1.AddTaskResponse Tema_II_2.ServiceReference1.WebService1Soap.AddTask(Tema_II_2.ServiceReference1.AddTaskRequest request) {
            return base.Channel.AddTask(request);
        }
        
        public int AddTask(string title, string description, System.DateTime deadline) {
            Tema_II_2.ServiceReference1.AddTaskRequest inValue = new Tema_II_2.ServiceReference1.AddTaskRequest();
            inValue.Body = new Tema_II_2.ServiceReference1.AddTaskRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.deadline = deadline;
            Tema_II_2.ServiceReference1.AddTaskResponse retVal = ((Tema_II_2.ServiceReference1.WebService1Soap)(this)).AddTask(inValue);
            return retVal.Body.AddTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema_II_2.ServiceReference1.AddTaskResponse> Tema_II_2.ServiceReference1.WebService1Soap.AddTaskAsync(Tema_II_2.ServiceReference1.AddTaskRequest request) {
            return base.Channel.AddTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema_II_2.ServiceReference1.AddTaskResponse> AddTaskAsync(string title, string description, System.DateTime deadline) {
            Tema_II_2.ServiceReference1.AddTaskRequest inValue = new Tema_II_2.ServiceReference1.AddTaskRequest();
            inValue.Body = new Tema_II_2.ServiceReference1.AddTaskRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.deadline = deadline;
            return ((Tema_II_2.ServiceReference1.WebService1Soap)(this)).AddTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema_II_2.ServiceReference1.UpdateTaskResponse Tema_II_2.ServiceReference1.WebService1Soap.UpdateTask(Tema_II_2.ServiceReference1.UpdateTaskRequest request) {
            return base.Channel.UpdateTask(request);
        }
        
        public bool UpdateTask(int taskId, string title, string description, System.DateTime deadline, bool isCompleted) {
            Tema_II_2.ServiceReference1.UpdateTaskRequest inValue = new Tema_II_2.ServiceReference1.UpdateTaskRequest();
            inValue.Body = new Tema_II_2.ServiceReference1.UpdateTaskRequestBody();
            inValue.Body.taskId = taskId;
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.deadline = deadline;
            inValue.Body.isCompleted = isCompleted;
            Tema_II_2.ServiceReference1.UpdateTaskResponse retVal = ((Tema_II_2.ServiceReference1.WebService1Soap)(this)).UpdateTask(inValue);
            return retVal.Body.UpdateTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema_II_2.ServiceReference1.UpdateTaskResponse> Tema_II_2.ServiceReference1.WebService1Soap.UpdateTaskAsync(Tema_II_2.ServiceReference1.UpdateTaskRequest request) {
            return base.Channel.UpdateTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema_II_2.ServiceReference1.UpdateTaskResponse> UpdateTaskAsync(int taskId, string title, string description, System.DateTime deadline, bool isCompleted) {
            Tema_II_2.ServiceReference1.UpdateTaskRequest inValue = new Tema_II_2.ServiceReference1.UpdateTaskRequest();
            inValue.Body = new Tema_II_2.ServiceReference1.UpdateTaskRequestBody();
            inValue.Body.taskId = taskId;
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.deadline = deadline;
            inValue.Body.isCompleted = isCompleted;
            return ((Tema_II_2.ServiceReference1.WebService1Soap)(this)).UpdateTaskAsync(inValue);
        }
        
        public bool DeleteTask(int taskId) {
            return base.Channel.DeleteTask(taskId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTaskAsync(int taskId) {
            return base.Channel.DeleteTaskAsync(taskId);
        }
    }
}
